# -*- coding: utf-8 -*-
QUESTIONS = [
    "PyTorch的Autograd机制是如何实现的？解释`torch.autograd.Function`的工作原理",
    "`torch.nn.Module`的`__call__`和`forward`有什么区别？为什么要这样设计？",
    "PyTorch的Dispatch机制是什么？`ATen`、`c10`、`torch.library`分别负责什么？",
    "如何实现一个自定义的CUDA算子并在PyTorch中调用？详细步骤是什么？",
    "PyTorch的内存池管理（Caching Allocator）策略是什么？如何分析和优化显存碎片？",
    "`torch.jit.trace`和`torch.jit.script`的区别？什么情况下会失败？",
    "PyTorch的`DataLoader`中`num_workers`设置多少合适？遇到过`too many open files`吗？",
    "解释PyTorch的`torch.distributed`中的`DDP`和`FSDP`的区别",
    "PyTorch 2.0的`torch.compile`背后的技术栈是什么？`TorchDynamo`、`AOTAutograd`、`Inductor`分别做什么？",
    "如何调试PyTorch的CUDA kernel launch失败？`CUDA_LAUNCH_BLOCKING=1`的原理？",
    "PyTorch的`hook`机制有哪些？`forward_pre_hook`和`backward_hook`的应用场景？",
    "如何实现模型的量化感知训练（QAT）？`torch.ao.quantization`的workflow是什么？",
    "PyTorch的`checkpoint`机制（梯度检查点）如何节省显存？计算开销在哪里？",
    "解释`torch.cuda.amp`的自动混合精度训练，什么情况下`GradScaler`会跳过参数更新？",
    "如何profile PyTorch模型的性能？`torch.profiler`和`nvprof`的使用经验？",
    "TensorFlow的XLA编译器优化了哪些场景？`jit_compile=True`的触发条件？",
    "TF的`tf.function`和PyTorch的`torch.jit`设计理念差异？",
    "XLA的HLO IR长什么样？如何阅读XLA的编译日志？",
    "TensorFlow的SavedModel格式和PyTorch的TorchScript对比？",
    "TF Serving的batching策略如何配置？遇到过哪些坑？",
    "用CUDA写一个简单的vector add，如何绑定到Python？",
    "Triton和CUDA的区别？什么时候用Triton更合适？",
    "如何编写一个融合算子（fused op）？以`layernorm + residual + activation`为例",
    "CUTLASS是什么？什么时候需要用它而不是手写CUDA？",
    "算子优化中的memory coalescing、bank conflict、occupancy分别指什么？",
    "如何用Nsight Compute分析kernel性能？关注哪些metrics？",
    "编写CUDA时如何平衡register使用和occupancy？",
    "什么是warp divergence？如何检测和避免？",
    "动态shape的算子如何优化？`vllm`中的`PagedAttention`是如何解决这个问题的？",
    "算子融合的收益如何评估？什么时候融合反而变慢？",
    "TVM的Ansor和MetaSchedule的区别？如何搜索最优schedule？",
    "MLIR的设计哲学是什么？`dialect`、`operation`、`pass`的概念？",
    "TorchInductor如何将PyTorch graph编译成Triton kernel？",
    "ONNX Runtime的图优化有哪些？`constant folding`、`operator fusion`等",
    "TensorRT的plugin开发流程？如何支持dynamic shape？",
    "解释`loop tiling`、`loop unrolling`、`vectorization`在编译器优化中的作用",
    "量化编译中的`PTQ`和`QAT`在编译器层面如何处理？",
    "稀疏化（sparsity）如何被编译器利用？`2:4 structured sparsity`的硬件支持？",
    "编译器的pass manager如何工作？`top-down` vs `bottom-up`遍历？",
    "如何为新的硬件后端添加编译器支持？以自定义AI芯片为例",
    "Apache TVM vs MLIR vs TorchDynamo，技术路线差异？",
    "编译时优化和运行时优化的权衡？`AOT` vs `JIT`？",
    "如何处理编译器的编译时间过长问题？缓存策略？",
    "`operator decomposing`和`operator fusion`的边界在哪里？",
    "编译器如何处理control flow（if/while）？`tracing` vs `symbolic execution`？",
    "DDP的`gradient bucketing`机制是什么？bucket size如何调优？",
    "DDP的`find_unused_parameters`参数什么时候需要设置？性能影响？",
    "FSDP的`sharding strategy`有哪些？`FULL_SHARD` vs `SHARD_GRAD_OP`？",
    "FSDP的`auto_wrap_policy`如何配置？`size_based` vs `module_based`？",
    "DeepSpeed的ZeRO-1/2/3分别offload了什么？显存节省和通信开销的trade-off？",
    "混合精度训练中的`loss scaling`在分布式场景下如何处理？",
    "梯度累积（gradient accumulation）在DDP中的正确实现方式？",
    "分布式sampler如何保证每个epoch的数据不重复？",
    "DDP的`SyncBatchNorm`原理？什么时候必须用？",
    "如何排查分布式训练中的hang问题？`NCCL_DEBUG=INFO`的输出如何解读？",
    "DDP的`torchrun`和`mp.spawn`启动方式的区别？",
    "多机多卡训练时，如何设置`NCCL_SOCKET_IFNAME`和`NCCL_IB_DISABLE`？",
    "梯度压缩（gradient compression）的方法有哪些？`fp16` vs `bf16` vs `1bit Adam`？",
    "异步训练（如`Hogwild!`）在工业界为什么很少用？",
    "如何实现自定义的分布式优化器？继承`torch.optim.Optimizer`的注意事项？",
    "Tensor Parallelism（TP）的`fused attention`实现细节？",
    "Megatron-LM的`column parallel`和`row parallel`的矩阵划分策略？",
    "Pipeline Parallelism（PP）的`bubble`问题如何量化？`GPipe` vs `PipeDream`？",
    "`interleaved pipeline`（如Megatron的1F1B）如何减少bubble？",
    "激活重计算（activation checkpointing）在PP中的特殊处理？",
    "如何平衡TP、PP、DP的维度划分？以175B模型为例",
    "`torch.distributed.pipeline.sync.Pipe`的使用限制？",
    "模型并行中的`all-gather`和`reduce-scatter`通信模式？",
    "流水线并行中的`micro-batch`大小如何影响吞吐？",
    "如何处理PP中的负载不均衡？`recompute`和`no-recompute`层的分配？",
    "3D并行（3D parallelism）的通信复杂度分析？",
    "序列并行（Sequence Parallelism）在长文本训练中的应用？",
    "Expert Parallelism在MoE模型中的all-to-all通信优化？",
    "零气泡流水线（Zero Bubble）的最新进展？",
    "如何profile分布式训练的通信开销？`torch.profiler`的`distributed` view？",
    "ZeRO-Offload如何将optimizer state offload到CPU？带宽瓶颈？",
    "`DeepSpeed-Infinity`如何利用NVMe扩展显存？",
    "激活检查点的`checkpoint_sequential`和`checkpoint`区别？",
    "显存碎片问题在分布式场景下更严重吗？如何解决？",
    "`torch.cuda.empty_cache()`的副作用？为什么不能频繁调用？",
    "如何估算大模型训练所需的显存？公式推导？",
    "`gradient checkpointing`和`activation compression`的结合？",
    "CPU offload和GPU计算的流水线重叠如何实现？",
    "多节点场景下的显存优化策略差异？",
    "显存优化的ROI如何评估？训练速度vs模型规模的trade-off？",
    "NCCL的`Tree`算法和`Ring`算法分别在什么场景下更快？",
    "如何计算all-reduce的通信量？公式是什么？",
    "`NVLink`、`InfiniBand`、`TCP`的带宽和延迟差异？",
    "多机训练中的网络拓扑感知？`NCCL_TOPO_FILE`？",
    "通信和计算重叠（overlap）的技术手段？`double buffering`？",
    "`torch.distributed`的`backend`选择：`nccl`、`gloo`、`mpi`？",
    "RDMA技术原理？`RoCE v1` vs `RoCE v2` vs `InfiniBand`？",
    "如何诊断网络拥塞导致的训练卡顿？`iftop`、`nicstat`？",
    "自定义通信算子的实现？`torch.distributed`的`reduce_op`？",
    "异构网络环境下的通信优化策略？",
    "TensorRT的`builder`和`runtime`工作流程？`plan`文件包含什么？",
    "TensorRT的`dynamic shape`优化技巧？`optimization profile`？",
    "TensorRT的`plugin`开发中，`IPluginV2DynamicExt`和`IPluginV2IOExt`区别？",
    "ONNX Runtime的`execution provider`有哪些？`CUDA`、`TensorRT`、`DirectML`？",
    "`torch.compile`的推理优化模式？`reduce-overhead` vs `max-autotune`？",
    "vLLM的`PagedAttention`核心思想？`block table`的数据结构？",
    "vLLM的`continuous batching`如何实现？和`static batching`的吞吐对比？",
    "vLLM的`prefix caching`机制？命中率如何提升？",
    "TensorRT-LLM的`in-flight batching`原理？",
    "FasterTransformer的`decoder`优化技术？`memory layout`优化？",
    "Hugging Face的`text-generation-inference`（TGI）架构？",
    "`llama.cpp`的量化策略？`Q4_0`、`Q5_K_M`的区别？",
    "移动端推理框架选择？`MNN`、`TNN`、`Paddle Lite`对比？",
    "推理引擎的`warmup`为什么重要？如何设计warmup策略？",
    "多stream推理的实现？`CUDA stream`的同步机制？",
    "推理batching的`padding`和`packing`策略？`FlashAttention`的变长支持？",
    "如何评估推理引擎的延迟分布？P50、P90、P99的优化重点？",
    "推理服务的`auto-scaling`策略？基于GPU利用率还是请求队列？",
    "多模型混部的资源隔离？`MPS`（Multi-Process Service）？",
    "推理引擎的`debug`模式？如何定位精度下降问题？",
    "`INT8`量化的`symmetric`和`asymmetric`区别？`per-tensor` vs `per-channel`？",
    "`SmoothQuant`的原理？为什么能同时保持权重和激活的量化精度？",
    "`AWQ`（Activation-aware Weight Quantization）的核心思想？",
    "`GPTQ`的`one-shot`量化流程？`OBQ`（Optimal Brain Quantization）？",
    "`GGUF`格式的量化级别？`Q4_K_M`适合什么场景？",
    "`FP8`量化的硬件支持？`H100`的`Transformer Engine`？",
    "量化校准（calibration）的数据集选择？多少样本足够？",
    "量化后的精度损失如何快速定位？layer-wise的sensitivity分析？",
    "`k-means`量化和非均匀量化的应用场景？",
    "二值化网络（BNN）在推理优化中的实际价值？",
    "知识蒸馏在推理优化中的作用？`MiniLLM`、`DistilBERT`？",
    "结构化剪枝和非结构化剪枝的硬件友好性？",
    "动态量化（Dynamic Quantization）和静态量化的runtime开销？",
    "量化算子的融合？`quantize-linear` + `matmul` + `dequantize`？",
    "混合精度推理的策略？哪些层必须保持`FP16`？",
    "Triton Inference Server的`model ensemble`如何使用？",
    "Triton的`dynamic batching`和`preferred batch size`配置？",
    "推理服务的`A/B testing`如何实现？模型版本管理？",
    "`Kubernetes` + `NVIDIA GPU Operator`的部署经验？",
    "GPU虚拟化方案？`MIG`（Multi-Instance GPU）的配置？",
    "推理请求的`priority scheduling`实现？`weighted fair queuing`？",
    "长文本请求的`preemption`策略？KV cache的swap out？",
    "推理服务的`health check`和`graceful degradation`？",
    "如何监控推理服务的`GPU memory`泄漏？",
    "推理模型的`hot reload`如何实现？零停机更新？",
    "`gRPC` vs `REST` for inference？性能差异和适用场景？",
    "推理批处理的`timeout`处理？部分结果返回？",
    "多租户场景下的资源配额管理？`quota`、`limit`、`request`？",
    "推理服务的`cost optimization`策略？Spot instance的使用？",
    "Edge deployment的挑战？模型加密、设备兼容性？",
    "Megatron-LM的代码结构？`megatron/core`的新设计？",
    "DeepSpeed的`ZeRO-Infinity`和`ZeRO-Offload`的代码入口？",
    "Colossal-AI的`Gemini`和`PatrickStar`的异同？",
    "FairScale的`FullyShardedDataParallel`（FSDP）实现细节？",
    "Hugging Face的`Accelerate`如何简化分布式训练？",
    "`torch.distributed.fsdp`的`limit_all_gathers`参数作用？",
    "大模型训练的`checkpoint`格式？`sharded checkpoint`的合并？",
    "训练恢复的`consistency`问题？如何确保resume后的loss一致？",
    "大模型训练的`data pipeline`优化？`WebDataset`、`tfrecord`？",
    "多模态大模型的训练基础设施挑战？图文数据的加载？",
    "RLHF训练的infra设计？`PPO`的分布式实现？",
    "MoE模型的`all-to-all`通信优化？`Tutel`、`FasterMoE`？",
    "长上下文训练（100K+ tokens）的显存优化？`Ring Attention`？",
    "训练任务的`fault tolerance`？`elastic training`的实现？",
    "大模型训练的`experiment tracking`？`Weights & Biases`、`MLflow`？",
    "大模型checkpoint的存储格式？`safetensors` vs `pytorch.bin`？",
    "分布式文件系统的选择？`Lustre`、`GPFS`、`Alluxio`？",
    "训练数据的`caching`策略？`SSD`作为`burst buffer`？",
    "大模型权重的高效加载？`memory mapping`、`lazy loading`？",
    "多节点间的checkpoint同步？`asynchronous checkpoint`？",
    "数据加载的`bottleneck`诊断？`nvidia-smi dmon`？",
    "`DALI`（NVIDIA Data Loading Library）的使用场景？",
    "训练数据的`sharding`策略？按文件vs按样本？",
    "云存储（S3、OSS）与本地存储的性能差异？`s3fs`？",
    "大规模数据集的`metadata`管理？`parquet`、`arrow`？",
    "Slurm的`sbatch`脚本编写？`gres`资源申请？",
    "Kubernetes的`volcano`调度器在AI场景的应用？",
    "训练任务的`gang scheduling`？`PyTorchJob`的`operator`？",
    "多租户集群的`resource quota`和`priority class`？",
    "GPU集群的`topology awareness`调度？`NVLink`拓扑？",
    "训练任务的`preemption`和`checkpoint & resume`？",
    "集群的`utilization`监控？`Prometheus` + `Grafana`？",
    "多集群的`federated learning`基础设施？",
    "训练任务的`cost accounting`？按GPU小时计费？",
    "集群的`heterogeneous GPU`管理？`A100`、`H100`、`4090`混部？",
    "`nvidia-smi`的`dmon`、`pmon`模式区别？",
    "Nsight Systems的timeline分析？如何识别`gap`？",
    "Nsight Compute的`roofline model`分析？",
    "PyTorch Profiler的`memory profiling`功能？",
    "`torch.autograd.profiler`的`record_shapes`和`profile_memory`？",
    "Chrome Trace Viewer解读PyTorch profiler输出？",
    "`perf`和`eBPF`在CPU侧的profiling？",
    "网络性能分析？`iperf`、`qperf`？",
    "存储IO分析？`fio`、`iostat`？",
    "如何构建端到端的性能监控dashboard？",
    "训练速度的`scaling efficiency`计算？理想vs实际？",
    "通信时间的`breakdown`分析？`all-reduce`、`all-gather`占比？",
    "算子级别的耗时分析？`torch.ops.aten`的dispatch？",
    "Python层面的profiling？`cProfile`、`py-spy`？",
    "性能回归（regression）的自动化检测？",
    "`FlashAttention`的`IO-aware`优化原理？`tiling`、`recomputation`？",
    "`FlashAttention-2`和`FlashAttention`的改进点？",
    "`xFormers`的`memory_efficient_attention`使用？",
    "`cuDNN`的`fused attention`如何调用？",
    "算子融合的边界判断？融合后register pressure过高？",
    "内存带宽bound vs 计算bound的判断？`arithmetic intensity`？",
    "`kernel fusion`的手动实现 vs 编译器自动生成？",
    "`CUDA Graph`的捕获和重放？`torch.cuda.make_graphed_callables`？",
    "动态shape的优化困境？`torch.compile`的`dynamic=True`？",
    "`torch.backends.cudnn.benchmark`的作用和副作用？",
    "CPU offload的`pin_memory`和`non_blocking`？",
    "数据预处理的`multi-processing`优化？`num_workers`调优？",
    "`DALI`的`GPU decoding`和`augmentation`？",
    "混合精度训练的`numerical stability`问题？",
    "`gradient accumulation`的`effective batch size`计算？",
    "大batch训练的`learning rate scaling`规则？",
    "`LARS`、`LAMB`优化器在大batch场景的应用？",
    "模型并行的`communication hiding`技术？",
    "`pipeline bubble`的数学分析和优化？",
    "稀疏attention的优化？`Sparse Transformer`、`Longformer`？",
    "设计一个支持1000卡规模的训练平台，核心组件有哪些？",
    "训练平台的`job scheduler`如何设计？`FIFO` vs `priority` vs `fair sharing`？",
    "分布式存储的选择？`Ceph`、`JuiceFS`、`GPFS`对比？",
    "训练容器的镜像管理？`layer caching`、`registry`优化？",
    "网络架构设计？`InfiniBand` vs `RoCE`？`fat-tree`拓扑？",
    "故障检测和自动恢复机制？`heartbeat`、`watchdog`？",
    "训练数据的`global shuffle`实现？`shuffle buffer`大小？",
    "模型仓库的设计？`版本管理`、`血缘追踪`？",
    "超参搜索（HPO）的基础设施？`Optuna`、`Ray Tune`集成？",
    "训练平台的`multi-tenancy`隔离？`namespace`、`cgroup`？",
    "资源碎片整理（defragmentation）策略？",
    "训练任务的`dry-run`和`profiling`模式？",
    "模型压缩服务的集成？`量化`、`剪枝`流水线？",
    "训练平台的`cost model`？预测任务耗时和资源需求？",
    "如何支持异构计算？`CPU`、`GPU`、`TPU`统一调度？",
    "训练平台的`SLA`定义？`job completion time`保证？",
    "数据隐私和合规？`联邦学习`基础设施？",
    "训练平台的`disaster recovery`？跨地域备份？",
    "模型`CI/CD`流水线？自动化测试、benchmark？",
    "训练平台的`observability`？日志、指标、链路追踪？",
    "设计一个支持10万QPS的大模型推理服务？",
    "推理服务的`auto-scaling`策略？`HPA`、`VPA`、`KEDA`？",
    "多模型`multi-tenancy`的GPU共享？`MPS` vs `MIG`？",
    "推理请求的`routing`策略？`least loaded`、`consistent hashing`？",
    "边缘推理的`model caching`策略？`CDN` for models？",
    "推理服务的`A/B testing`和`canary deployment`？",
    "长文本生成的`streaming`实现？`Server-Sent Events`？",
    "推理结果的`caching`策略？`prompt`级别的deduplication？",
    "多模态推理的`pipeline`设计？图文、视频？",
    "推理服务的`safety guardrails`？内容过滤、速率限制？",
    "模型`fine-tuning` as a service的架构？",
    "推理服务的`cost optimization`？`spot instance`、`batching`？",
    "模型`on-device`部署的infra支持？`Core ML`、`TFLite`？",
    "推理服务的`latency SLO`保证？`p99 < 100ms`如何实现？",
    "推理请求的`admission control`？防止过载？",
    "模型`ensemble`和`cascade`的架构设计？",
    "推理服务的`debuggability`？`request tracing`、`model versioning`？",
    "实时推理和离线推理的统一架构？",
    "推理服务的`security`？模型加密、API认证？",
    "推理平台的`carbon footprint`优化？绿色AI？",
    "写一个线程安全的`memory pool`，支持`allocate`和`free`",
    "CUDA的`__shared__` memory使用注意事项？`bank conflict`？",
    "实现一个`ring buffer`用于CPU-GPU异步数据传输",
    "`CUDA stream`和`event`的同步机制？`cudaStreamSynchronize`？",
    "`thrust`库的使用经验？`transform_reduce`？",
    "`CUTLASS`的`gemm`调用示例？`Epilogue`定制？",
    "`NCCL`的`all-reduce`实现？`ring`算法代码走读？",
    "`zero-copy` memory的使用场景？`cudaHostAlloc`？",
    "多GPU的`peer-to-peer`访问？`cudaDeviceEnablePeerAccess`？",
    "`CUDA Graph`的捕获条件？哪些操作不能捕获？",
    "`template metaprogramming`在CUDA优化中的应用？",
    "`RAII`模式管理CUDA资源？`unique_ptr` with custom deleter？",
    "`CUDA error`处理的最佳实践？`CUDA_CHECK`宏？",
    "`warp shuffle`指令的使用？`__shfl_sync`？",
    "`cooperative groups`的高级用法？`grid_group`？",
    "Python的`GIL`对多线程的影响？`multiprocessing` vs `threading`？",
    "`asyncio`在IO密集型任务中的应用？`aiohttp`？",
    "Python的`memory profiler`使用？`tracemalloc`？",
    "`Cython`和`pybind11`的区别？什么时候用？",
    "Python的`descriptor`协议？`property`的实现？",
    "`context manager`的`__enter__`和`__exit__`？",
    "`metaclass`在框架设计中的应用？`abc.ABCMeta`？",
    "Python的`import`机制？`sys.path`、`PYTHONPATH`？",
    "`pickle`的局限性和替代方案？`cloudpickle`、`dill`？",
    "Python代码的性能优化？`cProfile`、`line_profiler`？",
    "实现一个`LRU cache`，支持并发访问",
    "大文件的`external sort`实现？`k-way merge`？",
    "分布式`consistent hashing`的实现？`virtual node`？",
    "`bloom filter`在缓存中的应用？假阳性率计算？",
    "`skip list`的实现？`level`随机化策略？",
    "`B+ tree`在数据库中的应用？为什么适合磁盘？",
    "实现一个`rate limiter`？`token bucket` vs `leaky bucket`？",
    "字符串匹配的`KMP`算法？`prefix function`？",
    "图算法的`shortest path`？`Dijkstra`、`Bellman-Ford`？",
    "并查集（Union-Find）的实现？`path compression`？",
    "TCP和RDMA的对比？为什么AI训练需要RDMA？",
    "InfiniBand的`Verbs`编程？`ibv_post_send`？",
    "`RoCE v2`的`ECN`和`PFC`拥塞控制？",
    "多机训练的网络拓扑？`fat-tree`、`dragonfly`？",
    "`NCCL`的`bootstrap`和`transport`层？",
    "网络`jitter`对训练的影响？如何测量？",
    "`DPDK`在AI网络中的应用？",
    "`RDMA`的`memory registration`开销？",
    "网络虚拟化？`SR-IOV` vs `virtio`？",
    "跨可用区（AZ）训练的网络挑战？",
    "容器运行时？`containerd`、`cri-o`？",
    "Kubernetes的`CNI`插件？`Calico`、`Cilium`？",
    "GPU虚拟化技术？`vGPU`、`MIG`、`SR-IOV`？",
    "存储的`CSI`驱动开发？",
    "`etcd`在K8s中的作用？性能调优？",
]
